modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Suel-ki/Beautify-ReFoxed/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/beautify-refoxed"
logoFile="icon.png"
authors="Suel_ki, Pandarix"
description='''
Beautify adds lots of vanilla-styled ways to spice up your builds with custom models that'll fit right in to your houses etc.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
